name: my_trip_it
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^0.6.5
  amplify_api: ^0.6.5
  amplify_auth_cognito: ^0.6.5
  amplify_storage_s3: ^0.6.5
  amplify_datastore: ^0.6.5
  amplify_authenticator: ^0.2.0
  flutter_hooks: ^0.18.5+1
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  http: ^0.13.4
  intl: ^0.17.0
  go_router: ^4.1.0
  timelines: ^0.1.0
  file_picker: ^5.0.0
  url_launcher: ^6.1.5
  path_provider: ^2.0.11
  uuid: ^3.0.4
  path: ^1.8.1
  logger: ^1.1.0
  
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0-dev.9
  hooks_riverpod: ^2.0.0-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - images/amplify.png


